# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('event_code', models.CharField(max_length=20, verbose_name='event_code')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('phone_no', models.CharField(max_length=12, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254)),
                ('registration_id', models.CharField(max_length=20, verbose_name='Registration ID')),
                ('mode', models.CharField(choices=[('P', 'PayTM'), ('C', 'Cash')], max_length=1)),
            ],
        ),
    ]
