# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_participants_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='mode',
            field=models.CharField(choices=[('C', 'Cash'), ('P', 'PayTM')], max_length=1),
        ),
    ]
